// prettier-ignore
import { harmonies, qualities } from "./../constants.js";

export default {
    [qualities.unknown]: {
        0: harmonies.consonant,
        1: harmonies.dissonant,
        2: harmonies.dissonant,
        3: harmonies.semisonant,
        4: harmonies.semisonant,
        5: harmonies.consonant,
        6: harmonies.dissonant,
        7: harmonies.consonant,
        8: harmonies.semisonant,
        9: harmonies.semisonant,
        10: harmonies.dissonant,
        11: harmonies.dissonant,
    },
    [qualities.major]: {
        0: harmonies.consonant,
        1: harmonies.dissonant,
        2: harmonies.semisonant,
        3: harmonies.dissonant,
        4: harmonies.consonant,
        5: harmonies.consonant,
        6: harmonies.dissonant,
        7: harmonies.consonant,
        8: harmonies.dissonant,
        9: harmonies.semisonant,
        10: harmonies.dissonant,
        11: harmonies.semisonant,
    },
    [qualities.minor]: {
        0: harmonies.consonant,
        1: harmonies.dissonant,
        2: harmonies.semisonant,
        3: harmonies.consonant,
        4: harmonies.dissonant,
        5: harmonies.consonant,
        6: harmonies.dissonant,
        7: harmonies.consonant,
        8: harmonies.semisonant,
        9: harmonies.dissonant,
        10: harmonies.semisonant,
        11: harmonies.dissonant,
    },
    [qualities.diminished]: {
        0: harmonies.consonant,
        1: harmonies.dissonant,
        2: harmonies.semisonant,
        3: harmonies.consonant,
        4: harmonies.dissonant,
        5: harmonies.consonant,
        6: harmonies.dissonant,
        7: harmonies.consonant,
        8: harmonies.semisonant,
        9: harmonies.dissonant,
        10: harmonies.semisonant,
        11: harmonies.dissonant,
    },
    [qualities.augmented]: {
        0: harmonies.consonant,
        1: harmonies.dissonant,
        2: harmonies.semisonant,
        3: harmonies.consonant,
        4: harmonies.dissonant,
        5: harmonies.consonant,
        6: harmonies.dissonant,
        7: harmonies.consonant,
        8: harmonies.semisonant,
        9: harmonies.dissonant,
        10: harmonies.semisonant,
        11: harmonies.dissonant,
    },
}
